/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Code: typeof import('./components/Code/Index.vue')['default']
    CodeSwiper: typeof import('./components/Code/Swiper.vue')['default']
    copy: typeof import('./components/Limbo copy.vue')['default']
    CountDown: typeof import('./components/CountDown.vue')['default']
    Fly: typeof import('./components/Fly.vue')['default']
    Lang: typeof import('./components/lang.vue')['default']
    Limbo: typeof import('./components/Limbo.vue')['default']
    'Limbo copy': typeof import('./components/Limbo copy.vue')['default']
    NoticeBar: typeof import('./components/NoticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabbarTabbar: typeof import('./components/Tabbar/tabbar.vue')['default']
  }
}
